version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple:
    format: '%(levelname)s - %(message)s'
  verbose:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log
    maxBytes: 104857600  # 100MB
    backupCount: 10
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: verbose
    filename: logs/error.log
    maxBytes: 52428800  # 50MB
    backupCount: 5
    encoding: utf8

  database_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/database.log
    maxBytes: 104857600  # 100MB
    backupCount: 10
    encoding: utf8

  api_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/api.log
    maxBytes: 52428800  # 50MB
    backupCount: 5
    encoding: utf8

loggers:
  database:
    level: DEBUG
    handlers: [database_file]
    propagate: False

  api:
    level: DEBUG
    handlers: [api_file]
    propagate: False

  config:
    level: INFO
    handlers: [file]
    propagate: True

root:
  level: INFO
  handlers: [console, file, error_file]
